# Generated by Django 4.1 on 2022-11-08 05:16

from django.db import migrations

def populate_db(appreg, ed):
    convTable = appreg.get_model('unitconv', 'convTable')

    t = convTable(unit="T", float="0.0005")
    t.save()
    t_oz = convTable(unit="t_oz", float="14.5833")
    t_oz.save()
    oz = convTable(unit="oz", float="16")
    oz.save()
    g = convTable(unit="g", float="453.592")
    g.save()
    kg = convTable(unit="kg", float="0.453592")
    kg.save()
    lb = convTable(unit="lb", float="1")
    lb.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
